version: '3.8'

services:
  mxtoolbox:
    build: .
    container_name: mxtoolbox
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - DATABASE_FILE=/data/mxtoolbox.db
    volumes:
      - mxtoolbox_data:/data

volumes:
  mxtoolbox_data:
