from models.db_dmarc import dmarc_check_options, dmarc_policy_payload
from services.cloudflare_api import cf_is_configured, fetch_cf_dns_sets, find_cf_zone_id
from services.cloudflare_constants import (
    PENDING_MAIL_CHECK,
    get_webmail_target,
    mail_host,
    webmail_host,
)
from services.cloudflare_dns import public_dns_resolves
from services.dns_health import (
    _query_cname_target,
    apply_mail_hosting_context,
    check_dns_health,
    overall_from_checks,
)
from services.mxroute import (
    domain_on_mxroute,
    get_domain_mail_hosting,
    get_mxroute_dns_data,
    get_mxroute_verification_record,
)


def build_setup_health(domain):
    """DNS health for the setup wizard; supports domains not yet on MXroute."""
    domain = domain.lower().strip()
    on_mxroute = domain_on_mxroute(domain)
    verification_record = get_mxroute_verification_record()

    if on_mxroute:
        mx_dns_data = get_mxroute_dns_data(domain)
        if not mx_dns_data:
            return None
        health = check_dns_health(
            domain,
            mx_dns_data,
            verification_record=verification_record,
            **dmarc_check_options(domain),
        )
    else:
        health = {
            "domain": domain,
            "overall": "degraded",
            "checks": {},
        }
        if verification_record:
            partial = check_dns_health(
                domain,
                {},
                verification_record=verification_record,
                **dmarc_check_options(domain),
            )
            health["checks"]["verification"] = partial["checks"]["verification"]
        mail_labels = {
            "mail": "Mail server (CNAME)",
            "mx": "MX Records",
            "spf": "SPF (TXT)",
            "dkim": "DKIM (TXT)",
            "dmarc": "DMARC (TXT)",
        }
        for key, label in mail_labels.items():
            check = dict(PENDING_MAIL_CHECK)
            check["label"] = label
            if key == "dkim":
                check["message"] = (
                    "DKIM keys are generated by MXroute when the domain is registered. "
                    "Complete Step 3, then return here to add the record."
                )
            health["checks"][key] = check

        statuses = [c["status"] for c in health["checks"].values()]
        if any(s == "fail" for s in statuses):
            health["overall"] = "unhealthy"
        elif any(s in ("warn", "pending") for s in statuses):
            health["overall"] = "degraded"
        else:
            health["overall"] = "healthy"

    if on_mxroute:
        health["checks"]["mail"] = mail_health_check(domain)
        health["overall"] = overall_from_checks(health["checks"])
        health = apply_mail_hosting_context(health, get_domain_mail_hosting(domain))
        if cf_is_configured():
            # Optional, opt-in record: added after overall is computed so it never
            # degrades health or gets swept up by fix-all.
            health["checks"]["webmail"] = webmail_health_check(domain)

    health["on_mxroute"] = on_mxroute
    health["cf_configured"] = cf_is_configured()

    from services.mxroute import mx_request_raw

    _, mx_status = mx_request_raw("GET", "/domains")
    health["mxroute_reachable"] = mx_status == 200
    health["dmarc_policy"] = dmarc_policy_payload(domain)
    return health


def mail_health_check(domain):
    """Mail server CNAME (mail.<domain>): required for IMAP/SMTP custom hostname."""
    host = mail_host(domain)
    target = get_webmail_target()
    base = {"label": "Mail server (CNAME)", "expected_host": host, "expected": target}
    if not target:
        return {
            **base,
            "status": "skipped",
            "message": "MX_SERVER not configured — mail CNAME unavailable.",
        }

    public_target = _query_cname_target(host)
    zone_id = find_cf_zone_id(domain) if cf_is_configured() else None
    records = fetch_cf_dns_sets(zone_id)[2] if zone_id else []
    cname = next(
        (
            rec
            for rec in records
            if rec.get("type") == "CNAME"
            and rec.get("name", "").lower().rstrip(".") == host
        ),
        None,
    )

    if cname:
        found = cname.get("content", "").lower().rstrip(".")
        if found != target:
            return {
                **base,
                "status": "fail",
                "found": [found],
                "message": f"Mail CNAME {host} → {found} (expected {target}).",
            }
        if public_target == target or (
            public_target is None and public_dns_resolves(host)
        ):
            return {
                **base,
                "status": "pass",
                "found": [found],
                "message": f"Mail CNAME {host} → {found} (live).",
            }
        return {
            **base,
            "status": "pending",
            "found": [found],
            "message": f"Mail CNAME {host} → {found} in Cloudflare; waiting for public DNS to resolve.",
        }

    if public_target == target:
        return {
            **base,
            "status": "pass",
            "found": [public_target],
            "message": f"Mail CNAME {host} → {public_target} (live).",
        }
    if zone_id:
        return {
            **base,
            "status": "fail",
            "message": f"Mail CNAME {host} not deployed in Cloudflare.",
        }
    return {
        **base,
        "status": "fail",
        "message": f"Mail CNAME {host} missing or does not point to {target}.",
    }


def webmail_health_check(domain):
    """Webmail CNAME state: pass (deployed + resolves), pending (in CF, not live yet),
    or skipped (optional, not deployed). Never fails."""
    host = webmail_host(domain)
    target = get_webmail_target()
    base = {"label": "Webmail (CNAME)", "expected_host": host, "expected": target}
    if not target:
        return {
            **base,
            "status": "skipped",
            "message": "MX_SERVER not configured — webmail CNAME unavailable.",
        }

    zone_id = find_cf_zone_id(domain)
    records = fetch_cf_dns_sets(zone_id)[2] if zone_id else []
    cname = next(
        (
            rec
            for rec in records
            if rec.get("type") == "CNAME"
            and rec.get("name", "").lower().rstrip(".") == host
        ),
        None,
    )
    if not cname:
        return {
            **base,
            "status": "skipped",
            "message": f"Optional — webmail.{domain} not deployed.",
        }

    found = cname.get("content", "").lower().rstrip(".")
    if public_dns_resolves(host):
        return {
            **base,
            "status": "pass",
            "found": [found],
            "message": f"Webmail CNAME {host} → {found} (live).",
        }
    return {
        **base,
        "status": "pending",
        "found": [found],
        "message": f"Webmail CNAME {host} → {found} in Cloudflare; waiting for public DNS to resolve.",
    }
