import requests
from flask import current_app

from models.db import get_config_value, get_dmarc_record
from services.dns_health import check_dns_health, apply_mail_hosting_context, _normalize_txt, dkim_record_parts
from services.mxroute import (
    domain_on_mxroute,
    get_mxroute_verification_record,
    get_mxroute_dns_data,
    get_domain_mail_hosting,
    audit,
)

MAIL_DNS_RECORD_TYPES = ("mx", "spf", "dkim", "dmarc")
DNS_RECORD_TYPES = ("verification",) + MAIL_DNS_RECORD_TYPES

PENDING_MAIL_CHECK = {
    "status": "pending",
    "label": "",
    "message": "MXroute provides this record after the domain is registered (Step 3).",
}


def cf_is_configured():
    return bool(get_config_value("CF_API_TOKEN") and get_config_value("CF_ACCOUNT_ID"))


def cf_request(method, path, payload=None):
    cf_token = get_config_value("CF_API_TOKEN")
    if not cf_token:
        raise ValueError("Cloudflare API token not configured")

    url = f"https://api.cloudflare.com/client/v4{path}"
    headers = {
        "Authorization": f"Bearer {cf_token}",
        "Content-Type": "application/json"
    }

    if method not in ("GET", "POST", "PUT", "DELETE"):
        raise ValueError("Unsupported Cloudflare method")

    response = None
    try:
        response = requests.request(method, url, json=payload, headers=headers, timeout=30)
        response.raise_for_status()
        return response.json()
    except requests.exceptions.HTTPError as e:
        status = response.status_code if response is not None else "unknown"
        body = response.text[:200] if response is not None else ""
        current_app.logger.error(f"Cloudflare HTTP error {status}: {body}")
        try:
            return response.json()
        except (ValueError, AttributeError):
            raise ValueError(f"Cloudflare request failed ({status}): {body}") from e
    except requests.exceptions.RequestException as e:
        current_app.logger.error(f"Cloudflare request failed: {e}")
        raise


def build_setup_health(domain):
    """DNS health for the setup wizard; supports domains not yet on MXroute."""
    domain = domain.lower().strip()
    on_mxroute = domain_on_mxroute(domain)
    verification_record = get_mxroute_verification_record()

    if on_mxroute:
        mx_dns_data = get_mxroute_dns_data(domain)
        if not mx_dns_data:
            return None
        health = check_dns_health(
            domain,
            mx_dns_data,
            verification_record=verification_record,
            dmarc_expected=get_dmarc_record(),
        )
    else:
        health = {
            "domain": domain,
            "overall": "degraded",
            "checks": {},
        }
        if verification_record:
            partial = check_dns_health(
                domain,
                {},
                verification_record=verification_record,
                dmarc_expected=get_dmarc_record(),
            )
            health["checks"]["verification"] = partial["checks"]["verification"]
        mail_labels = {
            "mx": "MX Records",
            "spf": "SPF (TXT)",
            "dkim": "DKIM (TXT)",
            "dmarc": "DMARC (TXT)",
        }
        for key, label in mail_labels.items():
            check = dict(PENDING_MAIL_CHECK)
            check["label"] = label
            if key == "dkim":
                check["message"] = (
                    "DKIM keys are generated by MXroute when the domain is registered. "
                    "Complete Step 3, then return here to add the record."
                )
            health["checks"][key] = check

        statuses = [c["status"] for c in health["checks"].values()]
        if any(s == "fail" for s in statuses):
            health["overall"] = "unhealthy"
        elif any(s in ("warn", "pending") for s in statuses):
            health["overall"] = "degraded"
        else:
            health["overall"] = "healthy"

    if on_mxroute:
        health = apply_mail_hosting_context(health, get_domain_mail_hosting(domain))

    health["on_mxroute"] = on_mxroute
    health["cf_configured"] = cf_is_configured()
    
    from services.mxroute import mx_request_raw
    _, mx_status = mx_request_raw("GET", "/domains")
    health["mxroute_reachable"] = mx_status == 200
    return health


def ensure_cf_zone(domain, steps=None):
    cf_account = get_config_value("CF_ACCOUNT_ID")
    if steps is not None:
        steps.append("Querying Cloudflare for existing Zone...")
    zone_search = cf_request("GET", f"/zones?name={domain}")
    if zone_search.get("success") and zone_search.get("result"):
        zone_id = zone_search["result"][0]["id"]
        if steps is not None:
            steps.append(f"Found existing Cloudflare Zone (ID: {zone_id})")
        return zone_id

    if steps is not None:
        steps.append("Creating new Cloudflare Zone...")
    zone_create = cf_request("POST", "/zones", {
        "name": domain,
        "account": {"id": cf_account},
        "jump_start": True,
    })
    if not zone_create.get("success"):
        err_msg = zone_create.get("errors", [{}])[0].get("message", "Unknown Cloudflare error")
        raise ValueError(f"Cloudflare Zone creation failed: {err_msg}")
    zone_id = zone_create["result"]["id"]
    if steps is not None:
        steps.append(f"Created new Cloudflare Zone (ID: {zone_id})")
    return zone_id


def fetch_cf_dns_sets(zone_id):
    cf_dns_search = cf_request("GET", f"/zones/{zone_id}/dns_records?per_page=100")
    existing_records = cf_dns_search.get("result", []) if cf_dns_search.get("success") else []
    existing_mx = set()
    existing_txt = set()
    for rec in existing_records:
        rtype = rec.get("type")
        rname = rec.get("name", "").lower().rstrip(".")
        rcontent = rec.get("content", "").strip('"')
        if rtype == "MX":
            existing_mx.add((rname, rcontent.lower(), rec.get("priority")))
        elif rtype == "TXT":
            existing_txt.add((rname, rcontent))
    return existing_mx, existing_txt, existing_records


def cf_upsert_txt(zone_id, cf_name, fqdn, content, existing_records, existing_txt, steps, log_messages):
    """Create or update a TXT record when missing or incorrect. Returns added, updated, or skipped."""
    fqdn = fqdn.lower().rstrip(".")
    expected_norm = _normalize_txt(content)
    at_name = [
        rec for rec in existing_records
        if rec.get("type") == "TXT" and rec.get("name", "").lower().rstrip(".") == fqdn
    ]

    for rec in at_name:
        if _normalize_txt(rec.get("content", "")) == expected_norm:
            if steps is not None:
                steps.append(log_messages["skipped"])
            return "skipped"

    payload = {"type": "TXT", "name": cf_name, "content": content, "ttl": 3600}

    if at_name:
        result = cf_request("PUT", f"/zones/{zone_id}/dns_records/{at_name[0]['id']}", payload)
        if not result.get("success"):
            err_msg = result.get("errors", [{}])[0].get("message", "Unknown Cloudflare error")
            raise ValueError(f"Failed to update TXT record at {fqdn}: {err_msg}")
        for extra in at_name[1:]:
            cf_request("DELETE", f"/zones/{zone_id}/dns_records/{extra['id']}")
        existing_txt.difference_update({(n, c) for n, c in existing_txt if n == fqdn})
        existing_txt.add((fqdn, content))
        if steps is not None:
            steps.append(log_messages["updated"])
        return "updated"

    result = cf_request("POST", f"/zones/{zone_id}/dns_records", payload)
    if not result.get("success"):
        err_msg = result.get("errors", [{}])[0].get("message", "Unknown Cloudflare error")
        raise ValueError(f"Failed to add TXT record at {fqdn}: {err_msg}")
    existing_txt.add((fqdn, content))
    if steps is not None:
        steps.append(log_messages["added"])
    return "added"


def deploy_dns_record_to_cf(domain, zone_id, record_type, mx_dns_data, verification_record, existing_mx, existing_txt, existing_records, steps=None):
    """Deploy a single DNS record type to Cloudflare. Returns 'added' or 'skipped'."""
    domain_lower = domain.lower()

    if record_type == "verification":
        if not verification_record:
            raise ValueError("Failed to get verification key from MXroute")
        verify_name = verification_record.get("name")
        verify_value = verification_record.get("value")
        verify_name_full = f"{verify_name}.{domain}".lower()
        return cf_upsert_txt(
            zone_id, verify_name, verify_name_full, verify_value,
            existing_records, existing_txt, steps,
            {
                "skipped": "Verification TXT record already correct in Cloudflare",
                "added": "Verification TXT record deployed successfully",
                "updated": "Verification TXT record updated in Cloudflare",
            },
        )

    if record_type not in MAIL_DNS_RECORD_TYPES:
        raise ValueError(f"Unknown record type: {record_type}")

    if not mx_dns_data:
        raise ValueError("Mail DNS records require the domain to be registered on MXroute first")

    if record_type == "mx" and mx_dns_data.get("mx_records"):
        added = False
        for mx in mx_dns_data["mx_records"]:
            mx_host = mx["hostname"].lower().rstrip(".")
            mx_priority = mx["priority"]
            has_mx = any(
                rname == domain_lower and rcontent == mx_host
                and int(rpriority or 0) == int(mx_priority or 0)
                for rname, rcontent, rpriority in existing_mx
            )
            if not has_mx:
                cf_request("POST", f"/zones/{zone_id}/dns_records", {
                    "type": "MX",
                    "name": "@",
                    "content": mx["hostname"],
                    "priority": mx["priority"],
                    "ttl": 3600,
                })
                added = True
        if steps is not None:
            steps.append("MX records configured" if added else "MX records already exist (skipping)")
        return "added" if added else "skipped"

    if record_type == "spf" and mx_dns_data.get("spf"):
        spf_val = mx_dns_data["spf"]["value"]
        return cf_upsert_txt(
            zone_id, "@", domain_lower, spf_val,
            existing_records, existing_txt, steps,
            {
                "skipped": "SPF record already correct in Cloudflare",
                "added": "SPF record configured",
                "updated": "SPF record updated in Cloudflare",
            },
        )

    if record_type == "dkim" and mx_dns_data.get("dkim"):
        dkim_host_part, dkim_name_full = dkim_record_parts(mx_dns_data["dkim"], domain)
        dkim_val = mx_dns_data["dkim"]["value"]
        return cf_upsert_txt(
            zone_id, dkim_host_part, dkim_name_full, dkim_val,
            existing_records, existing_txt, steps,
            {
                "skipped": "DKIM record already correct in Cloudflare",
                "added": "DKIM record configured",
                "updated": "DKIM record updated in Cloudflare (previous value did not match MXroute)",
            },
        )

    if record_type == "dmarc":
        dmarc_val = get_dmarc_record()
        dmarc_name_full = f"_dmarc.{domain}".lower()
        return cf_upsert_txt(
            zone_id, "_dmarc", dmarc_name_full, dmarc_val,
            existing_records, existing_txt, steps,
            {
                "skipped": "DMARC record already correct in Cloudflare",
                "added": "DMARC record configured",
                "updated": "DMARC record updated in Cloudflare",
            },
        )

    if steps is not None:
        steps.append(f"No {record_type.upper()} data available from MXroute (skipping)")
    return "skipped"


def deploy_missing_dns_to_cf(domain, record_types=None):
    """Fix missing DNS records in Cloudflare for a domain."""
    steps = []
    if not cf_is_configured():
        raise ValueError("Cloudflare credentials not configured")

    health = build_setup_health(domain)
    if not health:
        raise ValueError("Failed to build DNS health state")

    if record_types is None:
        record_types = [
            key for key, check in health["checks"].items()
            if check["status"] in ("warn", "fail")
        ]
    else:
        record_types = [r.lower() for r in record_types]

    mail_requested = [r for r in record_types if r in MAIL_DNS_RECORD_TYPES]
    if mail_requested and not health["on_mxroute"]:
        raise ValueError(
            "MX, SPF, DKIM, and DMARC records require the domain to be registered on MXroute first. "
            "Complete Step 3, then return to Step 2."
        )

    if not record_types:
        return {"fixed": [], "skipped": list(health["checks"].keys()), "steps": ["All DNS records already look good"]}

    steps.append("Fetching existing DNS records from Cloudflare...")
    zone_id = ensure_cf_zone(domain, steps)
    existing_mx, existing_txt, existing_records = fetch_cf_dns_sets(zone_id)

    verification_record = get_mxroute_verification_record()
    mx_dns_data = get_mxroute_dns_data(domain) if health["on_mxroute"] else None

    fixed = []
    skipped = []
    for record_type in record_types:
        if record_type not in DNS_RECORD_TYPES:
            continue
        check = health["checks"].get(record_type, {})
        if check.get("status") == "pass":
            skipped.append(record_type)
            continue
        if check.get("status") == "pending":
            skipped.append(record_type)
            continue
        result = deploy_dns_record_to_cf(
            domain, zone_id, record_type, mx_dns_data, verification_record,
            existing_mx, existing_txt, existing_records, steps,
        )
        if result in ("added", "updated"):
            fixed.append(record_type)
        else:
            skipped.append(record_type)

    if fixed:
        audit("dns.fix", target=domain, records=fixed, outcome="updated")
    else:
        audit("dns.fix", target=domain, records=[], outcome="no_changes")
    return {"fixed": fixed, "skipped": skipped, "steps": steps}
