"""SQLite persistence — public API re-exported for backward compatibility."""

__all__ = [
    "ADMIN_PASSWORD_HASH_KEY",
    "ALL_PERMISSIONS",
    "DATABASE_FILE",
    "DEFAULT_PERMISSIONS",
    "ENV_ONLY_SECRET_KEYS",
    "MAPPING_FILE",
    "MASKED_SECRET_KEYS",
    "NOTIFICATION_SETTINGS_KEY",
    "RESET_TOKEN_TTL_HOURS",
    "SETTINGS_RESPONSE_KEYS",
    "SETTINGS_UI_KEYS",
    "_hash_reset_token",
    "_normalize_permissions",
    "admin_password_configured",
    "build_portal_host",
    "build_reset_portal_url",
    "clear_reset_portal_logo",
    "consume_reset_token",
    "create_reset_token",
    "delete_recovery_email",
    "get_active_reset_portal_for_mailbox_domain",
    "get_admin_notification_email",
    "get_admin_password_hash",
    "get_admin_user",
    "get_branding_dir",
    "get_config_value",
    "get_conn",
    "get_dmarc_record",
    "get_domain_dmarc_policy",
    "get_env_config",
    "get_notification_settings",
    "get_dns_health_state",
    "get_fleet_overview_state",
    "get_quota_monitor_state",
    "get_oidc_admin_group",
    "get_oidc_admin_users",
    "get_oidc_client_id",
    "get_oidc_client_secret",
    "get_oidc_discovery_url",
    "get_oidc_redirect_uri",
    "get_oidc_scopes",
    "get_or_create_secret_key",
    "get_recovery_email",
    "get_recovery_map",
    "get_reset_portal",
    "get_reset_portal_by_host",
    "get_reset_portal_cname_target",
    "get_reset_smtp_from",
    "get_reset_smtp_host",
    "get_reset_smtp_password",
    "get_reset_smtp_port",
    "get_reset_smtp_user",
    "get_user_contact_email",
    "get_users_contact_map",
    "init_db",
    "invalidate_settings_cache",
    "is_mailbox_reset_enabled",
    "is_oidc_enabled",
    "is_secret_configured",
    "list_reset_portals",
    "load_delegations_detail",
    "load_domain_mapping",
    "load_user_grants",
    "mask_settings_for_response",
    "migrate_settings_secrets",
    "parse_mailbox_email",
    "reset_smtp_use_tls",
    "resolve_notification_email",
    "save_notification_settings",
    "save_dns_health_state",
    "save_fleet_overview_state",
    "save_quota_monitor_state",
    "set_admin_password_hash",
    "set_recovery_email",
    "set_reset_portal_logo",
    "set_user_contact_email",
    "upsert_reset_portal",
    "set_domain_dmarc_policy",
    "clear_domain_dmarc_policy",
    "get_dmarc_record_for_domain",
    "use_secure_cookies",
    "verify_admin_password",
]

from models.db_constants import (
    ADMIN_PASSWORD_HASH_KEY,
    ALL_PERMISSIONS,
    DATABASE_FILE,
    DEFAULT_PERMISSIONS,
    ENV_ONLY_SECRET_KEYS,
    MAPPING_FILE,
    MASKED_SECRET_KEYS,
    NOTIFICATION_SETTINGS_KEY,
    RESET_TOKEN_TTL_HOURS,
    SETTINGS_RESPONSE_KEYS,
    SETTINGS_UI_KEYS,
)
from models.db_conn import get_conn, get_env_config
from models.db_delegations import (
    _normalize_permissions,
    get_admin_notification_email,
    get_or_create_secret_key,
    get_user_contact_email,
    get_users_contact_map,
    load_delegations_detail,
    load_domain_mapping,
    load_user_grants,
    resolve_notification_email,
    set_user_contact_email,
)
from models.db_portals import (
    build_portal_host,
    build_reset_portal_url,
    clear_reset_portal_logo,
    get_active_reset_portal_for_mailbox_domain,
    get_branding_dir,
    get_reset_portal,
    get_reset_portal_by_host,
    get_reset_portal_cname_target,
    list_reset_portals,
    set_reset_portal_logo,
    upsert_reset_portal,
)
from models.db_reset import (
    _hash_reset_token,
    consume_reset_token,
    create_reset_token,
    delete_recovery_email,
    get_recovery_email,
    get_recovery_map,
    parse_mailbox_email,
    set_recovery_email,
)
from models.db_dmarc import (
    clear_domain_dmarc_policy,
    get_domain_dmarc_policy,
    get_dmarc_record_for_domain,
    set_domain_dmarc_policy,
)
from models.db_settings import (
    admin_password_configured,
    get_admin_password_hash,
    get_admin_user,
    get_config_value,
    get_dmarc_record,
    get_oidc_admin_group,
    get_oidc_admin_users,
    get_oidc_client_id,
    get_oidc_client_secret,
    get_oidc_discovery_url,
    get_oidc_redirect_uri,
    get_oidc_scopes,
    get_reset_smtp_from,
    get_reset_smtp_host,
    get_reset_smtp_password,
    get_reset_smtp_port,
    get_reset_smtp_user,
    invalidate_settings_cache,
    is_mailbox_reset_enabled,
    is_oidc_enabled,
    is_secret_configured,
    mask_settings_for_response,
    migrate_settings_secrets,
    reset_smtp_use_tls,
    set_admin_password_hash,
    use_secure_cookies,
    verify_admin_password,
)
from models.db_notifications import (
    get_dns_health_state,
    get_fleet_overview_state,
    get_notification_settings,
    get_quota_monitor_state,
    save_dns_health_state,
    save_fleet_overview_state,
    save_notification_settings,
    save_quota_monitor_state,
)


def init_db(logger=None):
    from models.db_init import init_db as _init_db

    return _init_db(logger)
